name: app
description: 'A new Flutter project.'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  file_picker: ^8.1.4
  dio: ^5.7.0
  toastification: ^2.3.0
  go_router: ^14.6.0
  flutter_bloc: ^8.1.6
  shimmer: ^3.0.0
  permission_handler: ^11.3.1
  flutter_native_splash: ^2.4.2
  flutter_screenutil: ^5.9.3
  flutter_launcher_icons: ^0.14.1
  open_document: ^1.0.7
  shared_preferences: ^2.3.3
  get_it: ^8.0.2
  jwt_decoder: ^2.0.1
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  intl: ^0.18.1
  url_launcher: ^6.3.1
  hugeicons: ^0.0.7
  camera: ^0.11.0+2
  path: ^1.9.0
  video_player: ^2.9.2
  open_url: ^2.0.1
  open_filex: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: CircularStd
      fonts:
        - asset: assets/fonts/CircularStd/bold.ttf
          style: normal
          weight: 700
        - asset: assets/fonts/CircularStd/bold_italic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/CircularStd/light.ttf
          style: normal
          weight: 300
        - asset: assets/fonts/CircularStd/light_italic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/CircularStd/regular.ttf
          style: normal
          weight: 500
        - asset: assets/fonts/CircularStd/regular_italic.ttf
          style: italic
          weight: 500
